[item.default]
cmd = ['./swapview']
dir = '$name'
time_limit = 60
valid_percent = 10

[item.C]

[item.C++14]

[item.C++98]

[item.Chicken]

[item.CoffeeScript]
cmd = ['./swapview.coffee']

[item.CommonLisp]
cmd = ['./swapview.lisp']

[item.Go]

[item.Guile]
cmd = ['./swapview.scm']

[item.Haskell]

[item.Java]
cmd = ['java', 'SwapView']

[item.Lua51]
cmd = ['lua5.1', 'swapview.lua']
dir = 'Lua'

[item.Lua52]
cmd = ['lua', 'swapview.lua']
dir = 'Lua'

[item.LuaJIT]
cmd = ['luajit', 'swapview.lua']
dir = 'Lua'

[item.NodeJS]
cmd = ['./swapview.js']

[item.OCaml]

[item.Python2]
cmd = ['python2', 'swapview.py']
dir = 'Python'

[item.Python3]
cmd = ['python3', 'swapview.py']
dir = 'Python'

[item.Python3_bytes]
cmd = ['python3', 'swapview.py']

[item.Racket]
cmd = ['./swapview.rkt']

[item.Ruby]
cmd = ['./swapview.rb']

[item.Rust]
